### ISSUE TITLE
Querying small file returns empty response

### ISSUE THREAD

**Issue by ckulkarni-cribl** [a-ndrewh27/log-collector-sample#1]
Hi Andrew,

Thanks for submitting the assignment! I noticed querying small files is giving empty response. Here's the file and curl command used. Any idea whats going on?

```
❯ curl 'http://localhost:3000/logs?filename=one.log'              
{"logs":[]}%    
```
[one.log](https://github.com/a-ndrewh27/log-collector-sample/files/10060942/one.log)

**Comment by a-ndrewh27** [comment]
@ckulkarni-cribl thanks for finding the bug! I've just pushed a fix for this.

the error was happening because I did not handle for cases were files were smaller than `CHUNK_SIZE`.

thank you
